import type { AppProps } from 'next/app';
import createLocalFont from 'next/font/local';
import Head from 'next/head';

import { GlobalStyle } from '@/styles';
import { Layout, MapProvider } from '@/components';

const localFont = createLocalFont({ src: '../styles/omyu pretty.ttf' });

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>대똥여지도</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle />
      <main className={localFont.className}>
        <Layout>
          <MapProvider>
            <Component {...pageProps} />
          </MapProvider>
        </Layout>
      </main>
    </>
  );
}
