import type { AppProps } from 'next/app';
import createLocalFont from 'next/font/local';
import Head from 'next/head';

import { GlobalStyle } from '@/styles';
import { Layout, MapProvider } from '@/components';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

const localFont = createLocalFont({ src: '../styles/omyu pretty.ttf' });

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: 1,
      refetchOnWindowFocus: false,
    },
    mutations: {
      retry: 1,
    },
  },
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>대똥여지도</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QueryClientProvider client={queryClient}>
        <GlobalStyle />
        <main className={localFont.className}>
          <Layout>
            <MapProvider>
              <Component {...pageProps} />
            </MapProvider>
          </Layout>
        </main>
        <ReactQueryDevtools />
      </QueryClientProvider>
    </>
  );
}
